nameReference:
- kind: Issuer
  fieldSpecs:
  - path: spec/issuerRef/name
    kind: Certificate
- kind: Secret
  fieldSpecs:
  - path: spec/secretName
    kind: Certificate
  - path: spec/ca/secretName
    kind: Issuer
varReference:
- kind: Certificate
  path: spec/commonName
- kind: Certificate
  path: spec/dnsNames
